# Generated by Django 5.2.4 on 2025-07-26 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(choices=[('VISUAL', 'Visual'), ('AUDITORY', 'Auditory'), ('KINESTHETIC', 'Kinesthetic/Code-First'), ('READING', 'Reading/Writing')], default='VISUAL', max_length=20)),
                ('interests', models.TextField(blank=True, help_text="Comma-separated interests, e.g., 'finance, sports'")),
                ('badges', models.ManyToManyField(blank=True, to='learning.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
