# Generated by Django 5.2.4 on 2025-07-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_quiz_lesson_alter_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
