# Generated by Django 5.2.4 on 2025-07-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_studyplan_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='triggering_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.quizattempt'),
        ),
    ]
