# Generated by Django 5.2.4 on 2025-07-27 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_knowledgegap'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='The specific lesson this question is about.', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.lesson'),
        ),
    ]
