# Generated by Django 5.2.4 on 2025-07-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_mock_exam',
            field=models.BooleanField(default=False, help_text='Indicates if this is a comprehensive mock exam.'),
        ),
    ]
