# Generated by Django 5.2.4 on 2025-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_quiz_is_mock_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grading_rubric',
            field=models.TextField(blank=True, help_text='Rubric for grading open-ended questions.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple-Choice'), ('open-ended', 'Open-Ended')], default='multiple-choice', max_length=20),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='Score from 0.0 to 1.0 for open-ended answers', null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='open_ended_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
