# Generated by Django 5.2.4 on 2025-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_question_grading_rubric_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
