# Generated by Django 5.2.4 on 2025-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_useranswer_selected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('user_generated', 'User Generated'), ('daily_auto', 'Daily Auto-Quiz')], default='user_generated', max_length=20),
        ),
    ]
