# Generated by Django 5.2.4 on 2025-07-28 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_quiz_quiz_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mastery',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_mock_exam',
        ),
        migrations.AddField(
            model_name='mastery',
            name='last_tested_date',
            field=models.DateTimeField(blank=True, help_text='The last time the user was quizzed on this lesson.', null=True),
        ),
        migrations.AddField(
            model_name='mastery',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ai_insight',
            field=models.TextField(blank=True, help_text='Explanation from the AI on why this quiz was generated.', null=True),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='concept_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='mastery_score',
            field=models.FloatField(default=0.0, help_text='Mastery score from 0.0 to 1.0'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('lesson', 'Lesson Quiz'), ('daily', 'Daily Review Quiz'), ('weekly', 'Weekly Progress Quiz'), ('surprise', 'Surprise Quiz'), ('exam_pack', 'Pre-Exam Power Pack')], default='lesson', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user this quiz is for.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mastery',
            unique_together={('user', 'lesson')},
        ),
    ]
