# Generated by Django 5.2.4 on 2025-07-28 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_alter_mastery_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastery',
            name='concept_key',
        ),
        migrations.AddField(
            model_name='mastery',
            name='memory_strength',
            field=models.FloatField(default=0.0, help_text='A calculated score representing the durability of this memory.'),
        ),
        migrations.AddField(
            model_name='mastery',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='The AI-predicted optimal date for the next review.', null=True),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='mastery_score',
            field=models.FloatField(default=0.0, help_text='Current mastery score from 0.0 to 1.0, updated after every quiz.'),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_levels', to=settings.AUTH_USER_MODEL),
        ),
    ]
